---
  - name: Get infos on container
    docker_container_info:
      name: "{{ nginx_container_name }}"
    register: result
    check_mode: yes

  - name: uninstall Nginx
    import_tasks: uninstall.yml
    when: result.exists == true

  - name: Install Nginx
    import_tasks: install.yml
    when: result.exists == false
