---
  - name: Creating Nginx directory structure
    file:
      path: "{{nginx_default_dir}}/{{ item }}"
      state: directory
      mode: "{{ dir_mode }}"
      recurse: yes
    with_items: "{{ nginx_subdir }}"
