namespace: leonardoscampos
name: cloudmonitoring
version: 1.0.0
readme: README.md
authors:
- Leonardo Campos
description: "Collection for Cloud Monitoring"
license:
- 'MIT'
tags:
  - cloud
  - monitoring
  - zabbix
  - splunk
  - grafana
  - docker
  - elk
  - graylog

repository: "https://github.com/leonardoscampos/collections/cloud"
documentation: "https://github.com/leonardoscampos/collections/cloud"
homtepage: "https://github.com/leonardoscampos/"
issues: "https://github.com/leonardoscampos/collections/issues"
